export const medications = [
  {
    id: "tylenol",
    name: "Tylenol",
    genericName: "Acetaminophen",
    dosePerKg: 15,
    concentration: 32,
    formulationOptions: [
      { label: "160 mg/5 mL Liquid", mgPerMl: 32 },
      { label: "325 mg Tablet", tabletMg: 325, maxTablets: 2 },
      { label: "500 mg Tablet", tabletMg: 500, maxTablets: 2 },
    ],
    dispensingUnit: { label: "tsp (5 mL) per dose", volumeMl: 5 },
    adultDoseMg: 1000,
    adultMaxDailyMg: 4000,
    frequency: "Every 4–6 hours",
    maxDosePerKgPerDay: 75,
    minDosePerKg: 10,
    dosesPerDay: 4,
    warning: "Max 5 doses per 24 hours",
  },
  {
    id: "advil",
    name: "Advil",
    genericName: "Ibuprofen",
    dosePerKg: 7.5,
    concentration: 20,
    formulationOptions: [
      { label: "100 mg/5 mL Liquid", mgPerMl: 20 },
      { label: "200 mg Tablet", tabletMg: 200 },
      { label: "400 mg Tablet", tabletMg: 400 },
      { label: "600 mg Tablet", tabletMg: 600 },
      { label: "800 mg Tablet", tabletMg: 800 },
    ],
    dispensingUnit: { label: "tsp (5 mL) per dose", volumeMl: 5 },
    adultDoseMg: 800,
    adultMaxDailyMg: 3200,
    frequency: "Every 6–8 hours",
    maxDosePerKgPerDay: 30,
    minDosePerKg: 5,
    dosesPerDay: 3,
  },
  {
    id: "amoxicillin",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    dosePerKg: 13.3,
    concentration: 50,
    formulationOptions: [
      { label: "125 mg/5 mL Liquid", mgPerMl: 25 },
      { label: "200 mg/5 mL Liquid", mgPerMl: 40 },
      { label: "250 mg/5 mL Liquid", mgPerMl: 50 },
      { label: "400 mg/5 mL Liquid", mgPerMl: 80 },
      { label: "500 mg Tablet", tabletMg: 500 },
      { label: "875 mg Tablet", tabletMg: 875 },
    ],
    dispensingUnit: { label: "tsp (5 mL) per dose", volumeMl: 5 },
    frequency: "Every 8 hours",
    roundDown: true,
    dosingRegimens: [
      {
        id: "standard",
        label: "Standard — q8h (20–40 mg/kg/day)",
        dosePerKg: 13.3,
        minDosePerKg: 6.667,
        frequency: "Every 8 hours",
        maxSingleDoseMg: 500,
        maxDosePerKgPerDay: 40,
        dosesPerDay: 3,
      },
      {
        id: "high",
        label: "High Dose — q12h (25–45 mg/kg/day)",
        dosePerKg: 22.5,
        minDosePerKg: 12.5,
        frequency: "Every 12 hours",
        maxSingleDoseMg: 875,
        maxDosePerKgPerDay: 45,
        dosesPerDay: 2,
      },
    ],
  },
  {
    id: "azithromycin",
    name: "Azithromycin",
    genericName: "Azithromycin (Z-Pak)",
    dosePerKg: 10,
    concentration: 40,
    formulationOptions: [
      { label: "100 mg/5 mL Liquid", mgPerMl: 20 },
      { label: "200 mg/5 mL Liquid", mgPerMl: 40 },
      { label: "250 mg Tablet", tabletMg: 250 },
      { label: "500 mg Tablet", tabletMg: 500 },
    ],
    dispensingUnit: { label: "tsp (5 mL) per dose", volumeMl: 5 },
    adultDoseMg: 500,
    adultMaxDailyMg: 500,
    adultNote: "Z-Pak: 2 tabs (500 mg) on Day 1, then 1 tab (250 mg) on Days 2–5",
    frequency: "Once daily",
    maxDosePerKgPerDay: 10,
    dosesPerDay: 1,
    warning: "Max single dose 500 mg",
    dayDoses: [
      { id: "day1", label: "Day 1", dosePerKg: 10, maxMg: 500, frequency: "Once daily — Day 1" },
      { id: "day2plus", label: "Day 2+", dosePerKg: 5, maxMg: 250, frequency: "Once daily — Days 2–5" },
    ],
  },
  {
    id: "lidocaine",
    name: "Lidocaine",
    genericName: "Lidocaine 2% w/ Epi 1:100,000",
    dosePerKg: 4.4,
    concentration: 20,
    formulationOptions: [
      { label: "Carpule (1.7 mL)", mgPerMl: 20 },
    ],
    dispensingUnit: { label: "Carpule (1.7 mL)", volumeMl: 1.7 },
    frequency: "Single dose",
    absoluteMaxMg: 500,
    warning: "Max 4.4 mg/kg (2 mg/lb) with epinephrine",
  },
];
